# security:
#     encoders:
#         App\Entity\User: plaintext
#         FOS\UserBundle\Model\UserInterface: bcrypt
#     role_hierarchy:
#         ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
#         ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#     providers:
#         mainold:
#             entity: {class: App\Entity\User , property: username}
#         fos_userbundle:
#             id: fos_user.user_provider.username
#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false
#         main:
#             pattern: ^/
#             user_checker: security.user_checker
#             form_login:
#                 provider: fos_userbundle
#                 csrf_token_generator: security.csrf.token_manager
#             logout:       true
#             anonymous:    true
#     access_control:
#         # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         # - { path: ^/admin/, role: ROLE_ADMIN }
#         # - { path: ^/profile, roles: ROLE_USER }
