framework:
    default_locale: '%locale%' #m.G :cette variable est définie dans package/translation.yaml
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'       #m.G :cette variable est définie dans package/translation.yaml
                               #m.G :langue de repli 
