twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals: ##m.G : mettre disponible le tableau de langues dans config/servieshaml (parametters) dans toutes les vues twig       
        locales: '%app.locales%'
