index:
   path: /
   controller: App\Controller\PostController::index
pathFuncIcidonnelePath:
   path: /test
   controller: App\Controller\PostController::test

advert_index:
    path: /advert/{page} #parth('advert_index') =>index-advert
    controller: App\Controller\AdvertController::index
    defaults:
        page: 1 
    requirements: 
        page: '\d+'

advert_view:
    path: /advert/view/{id}
    controller: App\Controller\AdvertController::view
    requirements:
        id: '\d+'

advert_add:
    path: /advert/add
    controller: App\Controller\AdvertController::add

advert_edit:
    path: /advert/edit/{id}
    controller: App\Controller\AdvertController::edit
    requirements:
        id: '\d+'

advert_delete:
    path: /advert/delete/{id}
    controller: App\Controller\AdvertController::delete
    requirements: 
        id: '\d+'

advert_menu:
    path: /advert/menu
    controller: App\Controller\AdvertController::menuAction

advert_contact:
    path: /advert/contact
    controller: App\Controller\AdvertController::contactAction

login:
    path: /login
    defaults:
        _controller: App\Controller\SecurityController::loginAction

login_check:
    path: /login_check

logout:
    path: /logout

admin_create:
    path: /admin
    controller: App\Controller\AdminController::createAdmin
admin_list:
    path: /admin/list
    controller: App\Controller\AdminController::listAdmin
admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::deleteAdmin
    requirements:
        id: '\d+'