fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
index:
   path: /post
   controller: App\Controller\PostController::index

pathFuncIcidonnelePath:
   path: /test
   controller: App\Controller\PostController::test
#    user Manager
user_List:
   path: /userManager-list-of-users
   controller: App\Controller\PostController::userListManager
user_Create:
   path: /userManager-update-user
   controller: App\Controller\PostController::userCreate
user_Update:
   path: /userManager-update-user
   controller: App\Controller\PostController::userUpdate

advert_index:
    path: /advert/{page} #parth('advert_index') =>index-advert
    controller: App\Controller\AdvertController::index
    defaults:
        page: 1 
    requirements: 
        page: '\d+'

advert_view:
    path: /advert/view/{id}
    controller: App\Controller\AdvertController::view
    requirements:
        id: '\d+'

advert_add:
    path: /advert/add
    controller: App\Controller\AdvertController::add

advert_edit:
    path: /advert/edit/{id}
    controller: App\Controller\AdvertController::edit
    requirements:
        id: '\d+'

advert_delete:
    path: /advert/delete/{id}
    controller: App\Controller\AdvertController::delete
    requirements: 
        id: '\d+'

advert_menu:
    path: /advert/menu
    controller: App\Controller\AdvertController::menuAction

advert_contact:
    path: /advert/contact
    controller: App\Controller\AdvertController::contactAction

#Start AdminUsersController 
admin_list_users:
    path: /admin/list-users
    controller: App\Controller\AdminUsersController::listOfUsers

roles_user:
    path: /admin/roles-user/{id}
    controller: App\Controller\AdminUsersController::rolesOfUser
    requirements:
        id: '\d+'

admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminUsersController::deleteAdmin
    requirements:
        id: '\d+'

admin_edit:
    path: /admin/edit/{id}
    controller: App\Controller\AdminUsersController::editAdmin
    requirements:
        id: '\d+'
#End AdminUsersController  